
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "id numComandos : Comandos ComandoComandos : Comando\n\tComando : Ler\n\t\t\t| Escrever\n\t\t\t| Despejar\n\t\t\t| Atribuir\n\t Exp : Exp '+' Termo Exp : Exp '-' Termo Exp : Termo  Termo : Termo '*' Fator Termo : Termo '/' Fator Termo : Fator Fator : num  Fator : id  Fator : '(' Exp ')'  Ler : '?' id Escrever : '!' Exp Despejar : '!' '!'  Atribuir : id '=' Exp"
    
_lr_action_items = {'?':([0,1,2,3,4,5,6,10,11,13,14,15,16,17,18,20,26,27,28,29,30,],[7,7,-2,-3,-4,-5,-6,-1,-16,-18,-17,-9,-12,-13,-14,-19,-7,-8,-10,-11,-15,]),'!':([0,1,2,3,4,5,6,9,10,11,13,14,15,16,17,18,20,26,27,28,29,30,],[9,9,-2,-3,-4,-5,-6,13,-1,-16,-18,-17,-9,-12,-13,-14,-19,-7,-8,-10,-11,-15,]),'id':([0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,26,27,28,29,30,],[8,8,-2,-3,-4,-5,-6,11,18,-1,-16,18,-18,-17,-9,-12,-13,-14,18,-19,18,18,18,18,-7,-8,-10,-11,-15,]),'$end':([1,2,3,4,5,6,10,11,13,14,15,16,17,18,20,26,27,28,29,30,],[0,-2,-3,-4,-5,-6,-1,-16,-18,-17,-9,-12,-13,-14,-19,-7,-8,-10,-11,-15,]),'=':([8,],[12,]),'num':([9,12,19,21,22,23,24,],[17,17,17,17,17,17,17,]),'(':([9,12,19,21,22,23,24,],[19,19,19,19,19,19,19,]),'+':([14,15,16,17,18,20,25,26,27,28,29,30,],[21,-9,-12,-13,-14,21,21,-7,-8,-10,-11,-15,]),'-':([14,15,16,17,18,20,25,26,27,28,29,30,],[22,-9,-12,-13,-14,22,22,-7,-8,-10,-11,-15,]),')':([15,16,17,18,25,26,27,28,29,30,],[-9,-12,-13,-14,30,-7,-8,-10,-11,-15,]),'*':([15,16,17,18,26,27,28,29,30,],[23,-12,-13,-14,23,23,-10,-11,-15,]),'/':([15,16,17,18,26,27,28,29,30,],[24,-12,-13,-14,24,24,-10,-11,-15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Comandos':([0,],[1,]),'Comando':([0,1,],[2,10,]),'Ler':([0,1,],[3,3,]),'Escrever':([0,1,],[4,4,]),'Despejar':([0,1,],[5,5,]),'Atribuir':([0,1,],[6,6,]),'Exp':([9,12,19,],[14,20,25,]),'Termo':([9,12,19,21,22,],[15,15,15,26,27,]),'Fator':([9,12,19,21,22,23,24,],[16,16,16,16,16,28,29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Comandos","S'",1,None,None,None),
  ('Comandos -> Comandos Comando','Comandos',2,'p_Comandos','calc_yacc.py',39),
  ('Comandos -> Comando','Comandos',1,'p_Comandos_single','calc_yacc.py',43),
  ('Comando -> Ler','Comando',1,'p_Comando','calc_yacc.py',48),
  ('Comando -> Escrever','Comando',1,'p_Comando','calc_yacc.py',49),
  ('Comando -> Despejar','Comando',1,'p_Comando','calc_yacc.py',50),
  ('Comando -> Atribuir','Comando',1,'p_Comando','calc_yacc.py',51),
  ('Exp -> Exp + Termo','Exp',3,'p_Exp_add','calc_yacc.py',56),
  ('Exp -> Exp - Termo','Exp',3,'p_Exp_sub','calc_yacc.py',61),
  ('Exp -> Termo','Exp',1,'p_Exp_termo','calc_yacc.py',66),
  ('Termo -> Termo * Fator','Termo',3,'p_Termo_mul','calc_yacc.py',71),
  ('Termo -> Termo / Fator','Termo',3,'p_Termo_div','calc_yacc.py',76),
  ('Termo -> Fator','Termo',1,'p_Termo_fator','calc_yacc.py',85),
  ('Fator -> num','Fator',1,'p_Fator_num','calc_yacc.py',90),
  ('Fator -> id','Fator',1,'p_Fator_id','calc_yacc.py',94),
  ('Fator -> ( Exp )','Fator',3,'p_Fator_group','calc_yacc.py',99),
  ('Ler -> ? id','Ler',2,'p_Ler','calc_yacc.py',104),
  ('Escrever -> ! Exp','Escrever',2,'p_Escrever','calc_yacc.py',109),
  ('Despejar -> ! !','Despejar',2,'p_Despejar','calc_yacc.py',113),
  ('Atribuir -> id = Exp','Atribuir',3,'p_Atribuir','calc_yacc.py',117),
]
